spring:
  datasource:
    url: jdbc:h2:mem:noticedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

file:
  upload:
    dir: ./uploads

server:
  port: 8080 